nelmio_cors:
  defaults:
    allow_origin: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_methods: ["*"]
      allow_headers: ["*"]
      max_age: 3600

    "^/":
      origin_regex: true
      allow_origin: ["*"]
      allow_headers: ["*"]
      allow_methods: ["*"]
      max_age: 3600
      hosts: ['^api\.']
